// Please do not edit this file. It will be explained in a later Concept.

#ifndef LASAGNA_H
#define LASAGNA_H

extern const int expected_minutes_in_oven;

int remaining_minutes_in_oven(int actual_minutes_in_oven);

int preparation_time_in_minutes(int number_of_layers);

int elapsed_time_in_minutes(int number_of_layers, int actual_minutes_in_oven);

#endif
