[canonical-tests]

# pop gets element from the list
"7f7e3987-b954-41b8-8084-99beca08752c" = true

# push/pop respectively add/remove at the end of the list
"c3f67e5d-cfa2-4c3e-a18f-7ce999c3c885" = true

# shift gets an element from the list
"00ea24ce-4f5c-4432-abb4-cc6e85462657" = true

# shift gets first element from the list
"37962ee0-3324-4a29-b588-5a4c861e6564" = true

# unshift adds element at start of the list
"30a3586b-e9dc-43fb-9a73-2770cec2c718" = true

# pop, push, shift, and unshift can be used in any order
"042f71e4-a8a7-4cf0-8953-7e4f3a21c42d" = true

# count an empty list
"88f65c0c-4532-4093-8295-2384fb2f37df" = true

# count a list with items
"fc055689-5cbe-4cd9-b994-02e2abbb40a5" = true

# count is correct after mutation
"8272cef5-130d-40ea-b7f6-5ffd0790d650" = true

# popping to empty doesn't break the list
"229b8f7a-bd8a-4798-b64f-0dc0bb356d95" = true

# shifting to empty doesn't break the list
"4e1948b4-514e-424b-a3cf-a1ebbfa2d1ad" = true

# deletes the only element
"e8f7c600-d597-4f79-949d-8ad8bae895a6" = true

# deletes the element with the specified value from the list
"fd65e422-51f3-45c0-9fd0-c33da638f89b" = true

# deletes the element with the specified value from the list, re-assigns tail
"59db191a-b17f-4ab7-9c5c-60711ec1d013" = true

# deletes the element with the specified value from the list, re-assigns head
"58242222-5d39-415b-951d-8128247f8993" = true

# deletes the first of two elements
"ee3729ee-3405-4bd2-9bad-de0d4aa5d647" = true

# deletes the second of two elements
"47e3b3b4-b82c-4c23-8c1a-ceb9b17cb9fb" = true

# delete does not modify the list if the element is not found
"7b420958-f285-4922-b8f9-10d9dcab5179" = true

# deletes only the first occurrence
"7e04828f-6082-44e3-a059-201c63252a76" = true
