test.out:99-Bottles-of-Beer-on-The-Wall
	gcc -o 99-Bottles-of-Beer-on-The-Wall 99-Bottles-of-Beer-on-The-Wall.c

test:99-Bottles-of-Beer-on-The-Wall
	./99-Bottles-of-Beer-on-The-Wall

clean:99-Bottles-of-Beer-on-The-Wall
	rm -r 99-Bottles-of-Beer-on-The-Wall
