name: Configlet CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  configlet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

    - name: Fetch configlet
      uses: exercism/github-actions/configlet-ci@main

    - name: Configlet Linter
      run: configlet lint
