name: Configlet CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  configlet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

    - name: Fetch configlet
      uses: exercism/github-actions/configlet-ci@main

    - name: Configlet Linter
      run: configlet lint
